version: 2
jobs:
  test:
    docker:
      - image: circleci/php:7.3.3-stretch-node-browsers
    steps:
      - checkout
      - run: composer install
      - run: composer phpcs

workflows:
  version: 2
  check-wp-cs:
    jobs:
      - test:
        filters:
          branches:
            only: develop
