version: 2
jobs:
  build:
    branches:
      only:
        - master
  test:
    branches:
      only:
        - develop
    docker:
      - image: circleci/7.3.3-stretch-node-browsers
    steps:
      -
      - checkout
      - run: composer install
      - run: composer phpcs
